# Generated by Django 4.1.4 on 2023-03-27 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VRmaker', '0004_remove_filldetails_document_alter_filldetails_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filldetails',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
