# Generated by Django 4.1.4 on 2023-03-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRmaker', '0005_filldetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filldetails',
            name='phonenu',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
